# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-02 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
