# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-02 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nemo', '0003_auto_20180602_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='Message',
        ),
    ]
