# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-02 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nemo', '0004_auto_20180602_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Nemo.Room'),
        ),
    ]
