# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nemo', '0005_auto_20180602_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Room',
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Nemo.Room'),
            preserve_default=False,
        ),
    ]
