# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-03 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nemo', '0006_auto_20180602_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='admin',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
