# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-06-03 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nemo', '0008_auto_20180603_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
